"""empty message

Revision ID: 55228ee71ed7
Revises: 
Create Date: 2018-07-16 11:42:05.891197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55228ee71ed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=50), nullable=False),
    sa.Column('tmpt_lahir', sa.String(length=30), nullable=False),
    sa.Column('tgl_lahir', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.String(length=100), nullable=False),
    sa.Column('prodi', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
